### ISSUE TITLE
PHP >=8.0 incompatibility

### ISSUE THREAD

**Issue by mnlmaier** [aryehraber/statamic-color-extractor#8]
hi @aryehraber,

using your package for a website, thanks for the nice work! sadly as i had to move to php 8.0 i ran into a problem.

`Facade\Ignition\Exceptions\ViewException
Image must be a gd resource `

Here's a matching issue outlining the problem: https://github.com/thephpleague/color-extractor/pull/68#issuecomment-913042220

It would be great if you could keep an eye on it. Let me know if you do, i'll gladly buy you a beer or two!

**Comment by aryehraber** [comment]
Hi @mnlmaier, yeah I've been following the Issues/PRs in hopes it gets resolved soon, will update this Addon asap when it happens!

**Comment by mnlmaier** [comment]
great, thanks a lot! :)

**Comment by sebszocinski** [comment]
hey @aryehraber 👋  - facing the same here!

**Comment by aryehraber** [comment]
Hey @sebszocinski, sorry to hear that, hope it gets resolved soon!

**Comment by aryehraber** [comment]
I'm thinking of potentially forking the underlying package and patching it and using that for this Addon until it gets officially resolved. Will let you both know when I find the time, so that you can test it out!

**Comment by mnlmaier** [comment]
thanks a lot, really appreciated!

**Comment by aryehraber** [comment]
Hi guys, quick update regarding this issue...

I've managed to patch things up locally and it now works as expected, however I've not quite figured out how to package it up nicely from within the composer package to keep the upgrade simple for you (and other users).

I'll try and spend a little more time on it this week, and otherwise share the slightly more complex upgrade route so that you can get going. Will report back soon!

**Comment by mnlmaier** [comment]
sounds great — thanks for taking the time to figure this out :)

**Comment by aryehraber** [comment]
Hi again! Just released `v1.2.0` which should now work with PHP 8.0 🎉 

Please let me know if you notice any further issues. Enjoy!

**Comment by mnlmaier** [comment]
awesome! will check it out :) thanks so much!
